from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable, Iterator, List, Optional, Sequence, Set

from .model import ScanTarget
from .sim_prune import SimctlError, load_device_set_inventory


@dataclass(frozen=True)
class LocationSpec:
    category: str
    label: str
    relative_path: str
    cleanable: bool
    delete_mode: str
    note: str = ""


@dataclass(frozen=True)
class GlobLocationSpec:
    category: str
    label: str
    relative_glob: str
    cleanable: bool
    delete_mode: str
    note: str = ""


@dataclass(frozen=True)
class AbsoluteLocationSpec:
    category: str
    label: str
    path: str
    cleanable: bool
    delete_mode: str
    safety_root: str
    note: str = ""


FIXED_LOCATIONS = (
    LocationSpec(
        "xcode-derived-data",
        "Xcode DerivedData",
        "Library/Developer/Xcode/DerivedData",
        True,
        "contents",
        "Build artifacts generated by Xcode.",
    ),
    LocationSpec(
        "xcode-module-cache",
        "Xcode module cache",
        "Library/Developer/Xcode/ModuleCache.noindex",
        True,
        "contents",
        "Compiler module cache generated by Xcode.",
    ),
    LocationSpec(
        "xcode-documentation-cache",
        "Xcode documentation cache",
        "Library/Developer/Xcode/DocumentationCache",
        True,
        "contents",
        "Downloaded and generated Xcode documentation cache.",
    ),
    LocationSpec(
        "xcode-documentation-cache",
        "Xcode documentation index",
        "Library/Developer/Xcode/DocumentationIndex",
        True,
        "contents",
        "Generated Xcode documentation search index.",
    ),
    LocationSpec(
        "xcode-device-support",
        "Xcode iOS DeviceSupport",
        "Library/Developer/Xcode/iOS DeviceSupport",
        True,
        "contents",
        "Device support symbols and files recreated by Xcode when needed.",
    ),
    LocationSpec(
        "xcode-device-logs",
        "Xcode device logs",
        "Library/Developer/Xcode/DeviceLogs",
        True,
        "contents",
        "Imported device logs and diagnostic data. Close Xcode before cleaning.",
    ),
    LocationSpec(
        "xcode-test-devices",
        "XCTest simulator clones",
        "Library/Developer/XCTestDevices",
        True,
        "simctl-device-set",
        "Simulator clones generated by parallel tests. Stop tests and close Xcode before cleaning.",
    ),
    LocationSpec(
        "xcode-device-support",
        "Xcode tvOS DeviceSupport",
        "Library/Developer/Xcode/tvOS DeviceSupport",
        True,
        "contents",
        "Device support symbols and files recreated by Xcode when needed.",
    ),
    LocationSpec(
        "xcode-device-support",
        "Xcode watchOS DeviceSupport",
        "Library/Developer/Xcode/watchOS DeviceSupport",
        True,
        "contents",
        "Device support symbols and files recreated by Xcode when needed.",
    ),
    LocationSpec(
        "xcode-device-support",
        "Xcode visionOS DeviceSupport",
        "Library/Developer/Xcode/visionOS DeviceSupport",
        True,
        "contents",
        "Device support symbols and files recreated by Xcode when needed.",
    ),
    LocationSpec(
        "xcode-archives",
        "Xcode Archives",
        "Library/Developer/Xcode/Archives",
        False,
        "none",
        "App archives and dSYMs may be needed for releases and crash symbolication. Old exports can be archived to iCloud Drive after you verify they are no longer needed in Xcode Organizer.",
    ),
    LocationSpec(
        "simulator-caches",
        "CoreSimulator caches",
        "Library/Developer/CoreSimulator/Caches",
        True,
        "contents",
        "Shared simulator cache files.",
    ),
    LocationSpec(
        "simulator-caches",
        "CoreSimulator logs",
        "Library/Logs/CoreSimulator",
        True,
        "contents",
        "Simulator log files.",
    ),
    LocationSpec(
        "brew-cache",
        "Homebrew cache",
        "Library/Caches/Homebrew",
        True,
        "contents",
        "Downloaded bottles and formula cache.",
    ),
    LocationSpec(
        "pnpm-cache",
        "pnpm store",
        "Library/pnpm/store",
        True,
        "contents",
        "Global pnpm package store. Packages are redownloaded when needed.",
    ),
    LocationSpec(
        "pnpm-cache",
        "pnpm cache",
        "Library/Caches/pnpm",
        True,
        "contents",
        "pnpm cache files.",
    ),
    LocationSpec(
        "npm-cache",
        "npm cache",
        ".npm/_cacache",
        True,
        "contents",
        "npm package tarball cache.",
    ),
    LocationSpec(
        "npm-cache",
        "npm logs",
        ".npm/_logs",
        True,
        "contents",
        "npm debug logs.",
    ),
    LocationSpec(
        "node-tool-cache",
        "node-gyp cache",
        "Library/Caches/node-gyp",
        True,
        "contents",
        "Downloaded native Node build headers.",
    ),
    LocationSpec(
        "node-tool-cache",
        "TypeScript cache",
        "Library/Caches/typescript",
        True,
        "contents",
        "TypeScript language service and tooling cache.",
    ),
    LocationSpec(
        "node-tool-cache",
        "Bun cache",
        "Library/Caches/bun",
        True,
        "contents",
        "Bun package and tooling cache.",
    ),
    LocationSpec(
        "node-tool-cache",
        "Bun install cache",
        ".bun/install/cache",
        True,
        "contents",
        "Downloaded Bun packages. Packages are fetched again when needed.",
    ),
    LocationSpec(
        "python-cache",
        "pip cache",
        "Library/Caches/pip",
        True,
        "contents",
        "pip download and wheel cache.",
    ),
    LocationSpec(
        "python-cache",
        "pip cache",
        ".cache/pip",
        True,
        "contents",
        "pip download and wheel cache.",
    ),
    LocationSpec(
        "python-cache",
        "Poetry cache",
        "Library/Caches/pypoetry",
        True,
        "contents",
        "Poetry package cache.",
    ),
    LocationSpec(
        "python-cache",
        "Poetry cache",
        ".cache/pypoetry",
        True,
        "contents",
        "Poetry package cache.",
    ),
    LocationSpec(
        "swiftpm-cache",
        "SwiftPM cache",
        "Library/Caches/org.swift.swiftpm",
        True,
        "contents",
        "Swift Package Manager cache.",
    ),
    LocationSpec(
        "go-cache",
        "Go build cache",
        "Library/Caches/go-build",
        True,
        "contents",
        "Go build cache.",
    ),
    LocationSpec(
        "go-cache",
        "Go module cache",
        "go/pkg/mod",
        True,
        "contents",
        "Downloaded Go modules.",
    ),
    LocationSpec(
        "rust-cache",
        "Cargo registry cache",
        ".cargo/registry",
        True,
        "contents",
        "Cargo registry index, source, and crate cache.",
    ),
    LocationSpec(
        "rust-cache",
        "Cargo git cache",
        ".cargo/git",
        True,
        "contents",
        "Cargo git dependency cache.",
    ),
    LocationSpec(
        "gradle-cache",
        "Gradle cache",
        ".gradle/caches",
        True,
        "contents",
        "Gradle dependency and build caches.",
    ),
    LocationSpec(
        "gradle-cache",
        "Gradle daemons",
        ".gradle/daemon",
        True,
        "contents",
        "Gradle daemon logs and state.",
    ),
    LocationSpec(
        "gradle-cache",
        "Gradle wrapper distributions",
        ".gradle/wrapper/dists",
        True,
        "contents",
        "Downloaded Gradle wrapper distributions.",
    ),
    LocationSpec(
        "browser-cache",
        "Google browser caches",
        "Library/Caches/Google",
        True,
        "contents",
        "Browser cache files. Close browsers before cleaning for best results.",
    ),
    LocationSpec(
        "browser-cache",
        "Chrome on-device AI model",
        "Library/Application Support/Google/Chrome/OptGuideOnDeviceModel",
        True,
        "contents",
        "Downloaded Chrome AI model. Chrome can download it again when storage requirements are met.",
    ),
    LocationSpec(
        "browser-cache",
        "Chrome component cache",
        "Library/Application Support/Google/Chrome/component_crx_cache",
        True,
        "contents",
        "Downloaded Chrome components. Close Chrome before cleaning.",
    ),
    LocationSpec(
        "browser-cache",
        "Brave component cache",
        "Library/Application Support/BraveSoftware/Brave-Browser/component_crx_cache",
        True,
        "contents",
        "Downloaded Brave components. Close Brave before cleaning.",
    ),
    LocationSpec(
        "updater-cache",
        "Google Updater package cache",
        "Library/Application Support/Google/GoogleUpdater/crx_cache",
        True,
        "contents",
        "Downloaded Google update packages.",
    ),
    LocationSpec(
        "editor-cache",
        "Cursor cache",
        "Library/Application Support/Cursor/Cache",
        True,
        "contents",
        "Editor web cache. Close Cursor before cleaning.",
    ),
    LocationSpec(
        "editor-cache",
        "Cursor version cache",
        "Library/Application Support/Cursor/CachedData",
        True,
        "contents",
        "Cached editor resources. Close Cursor before cleaning.",
    ),
    LocationSpec(
        "editor-cache",
        "Cursor logs",
        "Library/Application Support/Cursor/logs",
        True,
        "contents",
        "Cursor diagnostic logs.",
    ),
    LocationSpec(
        "editor-cache",
        "Windsurf cache",
        "Library/Application Support/Windsurf/Cache",
        True,
        "contents",
        "Editor web cache. Close Windsurf before cleaning.",
    ),
    LocationSpec(
        "editor-cache",
        "Windsurf version cache",
        "Library/Application Support/Windsurf/CachedData",
        True,
        "contents",
        "Cached editor resources. Close Windsurf before cleaning.",
    ),
    LocationSpec(
        "editor-cache",
        "Codex app cache",
        "Library/Application Support/Codex/Cache",
        True,
        "contents",
        "Codex desktop web cache. Close Codex before cleaning.",
    ),
    LocationSpec(
        "editor-cache",
        "Codex component cache",
        "Library/Application Support/Codex/component_crx_cache",
        True,
        "contents",
        "Downloaded Codex desktop browser components. Close Codex before cleaning.",
    ),
    LocationSpec(
        "wallpaper-cache",
        "Downloaded aerial wallpapers",
        "Library/Application Support/com.apple.wallpaper/aerials/videos",
        True,
        "contents",
        "Downloaded wallpaper videos. macOS may download selected wallpapers again.",
    ),
    LocationSpec(
        "browser-cache",
        "Brave browser caches",
        "Library/Caches/BraveSoftware",
        True,
        "contents",
        "Browser cache files. Close browsers before cleaning for best results.",
    ),
    LocationSpec(
        "browser-cache",
        "Firefox browser caches",
        "Library/Caches/Firefox",
        True,
        "contents",
        "Browser cache files. Close browsers before cleaning for best results.",
    ),
    LocationSpec(
        "browser-cache",
        "Safari cache",
        "Library/Caches/com.apple.Safari",
        True,
        "contents",
        "Browser cache files. Close browsers before cleaning for best results.",
    ),
    LocationSpec(
        "docker",
        "Docker Desktop logs",
        "Library/Containers/com.docker.docker/Data/log",
        False,
        "none",
        "Reported only. Prefer Docker's own prune commands for Docker data.",
    ),
    LocationSpec(
        "docker",
        "Docker Desktop VM data",
        "Library/Containers/com.docker.docker/Data/vms",
        False,
        "none",
        "Reported only. Deleting this directly can remove images and volumes.",
    ),
    LocationSpec(
        "dev-tool-cache",
        "Codex runtime cache",
        ".cache/codex-runtimes",
        False,
        "none",
        "Reported only. Close active Codex sessions before manually clearing downloaded runtimes.",
    ),
    LocationSpec(
        "developer-data",
        "Codex task history",
        ".codex/sessions",
        False,
        "none",
        "Preserve unless intentionally archiving old task history. Do not move active Codex state into iCloud.",
    ),
    LocationSpec(
        "icloud-candidate",
        "Codex generated images",
        ".codex/generated_images",
        False,
        "none",
        "Review old generated images. Finished images can be copied to iCloud Drive, then Remove Download in Finder.",
    ),
    LocationSpec(
        "device-backups",
        "Local Apple device backups",
        "Library/Application Support/MobileSync/Backup",
        False,
        "none",
        "Review in Finder or macOS Storage settings. Prefer iCloud Backup before deleting a needed local backup.",
    ),
)

SYSTEM_LOCATIONS = (
    AbsoluteLocationSpec(
        "installed-apps",
        "Installed applications",
        "/Applications",
        False,
        "none",
        "/Applications",
        "Review large unused apps in System Settings > General > Storage > Applications; uninstall through Finder or the app's uninstaller.",
    ),
    AbsoluteLocationSpec(
        "simulator-dyld-cache",
        "CoreSimulator dyld shared caches",
        "/Library/Developer/CoreSimulator/Caches/dyld",
        True,
        "simctl-runtime-cache",
        "/Library/Developer/CoreSimulator/Caches",
        "Generated simulator runtime caches removed through simctl. Close Xcode and Simulator first.",
    ),
    AbsoluteLocationSpec(
        "developer-tools",
        "Command Line Tools installation",
        "/Library/Developer/CommandLineTools",
        False,
        "none",
        "/Library/Developer",
        "Reported only. Keep if Homebrew or command-line builds rely on it; uninstall through Apple's supported tooling if no longer needed.",
    ),
)

GLOB_LOCATIONS = (
    GlobLocationSpec(
        "simulator-caches",
        "Simulator device caches",
        "Library/Developer/CoreSimulator/Devices/*/data/Library/Caches",
        True,
        "contents",
        "Per-device simulator app cache directories.",
    ),
    GlobLocationSpec(
        "project-derived-data",
        "Project-local Xcode DerivedData",
        "*/DerivedData*",
        True,
        "tree",
        "Generated Xcode build products. The directory must contain Xcode's DerivedData markers.",
    ),
    GlobLocationSpec(
        "project-derived-data",
        "Project-local Xcode DerivedData",
        "*/Build/DerivedData",
        True,
        "tree",
        "Generated Xcode build products. The directory must contain Xcode's DerivedData markers.",
    ),
    GlobLocationSpec(
        "project-derived-data",
        "Project-local Xcode DerivedData",
        "*/build/DerivedData",
        True,
        "tree",
        "Generated Xcode build products. The directory must contain Xcode's DerivedData markers.",
    ),
)

DEFAULT_SEARCH_ROOT_NAMES = (
    "Developer",
    "Projects",
    "Code",
    "src",
    "work",
    "Sites",
    "Documents/GitHub",
)

SKIPPED_DIR_NAMES = {
    ".git",
    ".hg",
    ".svn",
    ".tox",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "Library",
}

MIN_REPORTED_TARGET_SIZE_BYTES = 1024 * 1024


def scan(
    home: Optional[Path] = None,
    cwd: Optional[Path] = None,
    search_roots: Optional[Sequence[Path]] = None,
    include_node_modules: bool = True,
    include_project_derived_data: bool = True,
    node_modules_older_than: Optional[timedelta] = None,
    now: Optional[datetime] = None,
    categories: Optional[Set[str]] = None,
) -> List[ScanTarget]:
    home = (home or Path.home()).expanduser()
    cwd = (cwd or Path.cwd()).expanduser()
    now = now or datetime.now(timezone.utc)

    targets: List[ScanTarget] = []
    targets.extend(_scan_fixed_locations(home, categories=categories))
    if _is_default_home(home):
        targets.extend(_scan_system_locations(categories=categories))
    targets.extend(
        _scan_glob_locations(
            home,
            categories=categories,
            include_project_derived_data=include_project_derived_data,
        )
    )

    if include_node_modules and (categories is None or "node-modules" in categories):
        roots = list(search_roots) if search_roots else default_search_roots(home, cwd)
        targets.extend(_scan_node_modules(roots, node_modules_older_than, now, home))

    return sorted(_unique_targets(targets), key=lambda item: item.size_bytes, reverse=True)


def default_search_roots(home: Path, cwd: Path) -> List[Path]:
    roots = [cwd]
    for name in DEFAULT_SEARCH_ROOT_NAMES:
        roots.append(home / name)
    return unique_existing_roots(roots, home)


def _unique_targets(targets: Iterable[ScanTarget]) -> List[ScanTarget]:
    seen: Set[object] = set()
    result: List[ScanTarget] = []
    for target in targets:
        try:
            target_stat = os.stat(target.path, follow_symlinks=False)
            key: object = (target_stat.st_dev, target_stat.st_ino)
        except OSError:
            key = _safe_resolve(target.path) or target.path
        if key in seen:
            continue
        seen.add(key)
        result.append(target)
    return result


def unique_existing_roots(roots: Iterable[Path], home: Optional[Path] = None) -> List[Path]:
    seen: Set[Path] = set()
    result: List[Path] = []
    home_resolved = _safe_resolve(home) if home else None
    filesystem_root = Path("/").resolve()

    for root in roots:
        path = root.expanduser()
        if not path.exists() or not path.is_dir():
            continue
        resolved = _safe_resolve(path)
        if resolved is None or resolved in seen:
            continue
        if resolved == filesystem_root:
            continue
        if home_resolved is not None and _is_same_or_parent(resolved, home_resolved):
            continue
        seen.add(resolved)
        result.append(path)

    return result


def _scan_fixed_locations(
    home: Path, categories: Optional[Set[str]] = None
) -> Iterator[ScanTarget]:
    for spec in FIXED_LOCATIONS:
        if categories is not None and spec.category not in categories:
            continue
        path = home / spec.relative_path
        if path.exists():
            target = _target_from_path(
                path=path,
                category=spec.category,
                label=spec.label,
                cleanable=spec.cleanable,
                delete_mode=spec.delete_mode,
                note=spec.note,
                safety_root=home,
            )
            if target:
                yield target


def _scan_glob_locations(
    home: Path,
    categories: Optional[Set[str]] = None,
    include_project_derived_data: bool = True,
) -> Iterator[ScanTarget]:
    for spec in GLOB_LOCATIONS:
        if categories is not None and spec.category not in categories:
            continue
        if spec.category == "project-derived-data" and not include_project_derived_data:
            continue
        for path in home.glob(spec.relative_glob):
            if path.exists():
                target = _target_from_path(
                    path=path,
                    category=spec.category,
                    label=spec.label,
                    cleanable=spec.cleanable,
                    delete_mode=spec.delete_mode,
                    note=spec.note,
                    safety_root=home,
                )
                if target:
                    yield target


def _scan_system_locations(
    categories: Optional[Set[str]] = None,
) -> Iterator[ScanTarget]:
    for spec in SYSTEM_LOCATIONS:
        if categories is not None and spec.category not in categories:
            continue
        path = Path(spec.path)
        if not path.exists():
            continue
        target = _target_from_path(
            path=path,
            category=spec.category,
            label=spec.label,
            cleanable=spec.cleanable,
            delete_mode=spec.delete_mode,
            note=spec.note,
            safety_root=Path(spec.safety_root),
        )
        if target:
            yield target


def _scan_node_modules(
    roots: Sequence[Path],
    older_than: Optional[timedelta],
    now: datetime,
    home: Path,
) -> Iterator[ScanTarget]:
    cutoff = now - older_than if older_than else None
    for root in unique_existing_roots(roots, home=home):
        for path in find_node_modules(root):
            modified_at = modified_time(path)
            if cutoff and modified_at and modified_at > cutoff:
                continue
            target = _target_from_path(
                path=path,
                category="node-modules",
                label="node_modules",
                cleanable=True,
                delete_mode="tree",
                note="Project dependencies. Reinstall with npm, yarn, or pnpm.",
                safety_root=root,
            )
            if target:
                yield target


def find_node_modules(root: Path) -> Iterator[Path]:
    root = root.expanduser()
    if not root.exists() or not root.is_dir():
        return
    if root.name == "node_modules":
        yield root
        return

    for dirpath, dirnames, _filenames in os.walk(root):
        current = Path(dirpath)
        if current.name in SKIPPED_DIR_NAMES:
            dirnames[:] = []
            continue

        if "node_modules" in dirnames:
            node_modules = current / "node_modules"
            yield node_modules
            dirnames.remove("node_modules")

        dirnames[:] = [name for name in dirnames if name not in SKIPPED_DIR_NAMES]


def _target_from_path(
    path: Path,
    category: str,
    label: str,
    cleanable: bool,
    delete_mode: str,
    note: str,
    safety_root: Optional[Path],
) -> Optional[ScanTarget]:
    if category == "project-derived-data" and not _is_project_derived_data_path(
        path, safety_root
    ):
        return None
    size, include_when_small = _location_measurement(path, category)
    if size < MIN_REPORTED_TARGET_SIZE_BYTES and not include_when_small:
        return None
    modified_at = modified_time(path)
    return ScanTarget(
        category=category,
        label=label,
        path=path,
        size_bytes=size,
        modified_at=modified_at,
        cleanable=cleanable,
        delete_mode=delete_mode,
        note=note,
        safety_root=safety_root,
    )


def _location_measurement(path: Path, category: str) -> tuple[int, bool]:
    if category != "xcode-test-devices":
        return path_size(path), False

    default_device_set = Path.home() / "Library/Developer/XCTestDevices"
    try:
        is_default_device_set = path.expanduser().resolve() == default_device_set.resolve()
    except OSError:
        is_default_device_set = False
    if not is_default_device_set:
        return path_size(path), False

    try:
        inventory = load_device_set_inventory(path)
    except (OSError, SimctlError, ValueError):
        return path_size(path), False

    # simctl's dataPathSize is the logical size of each APFS clone. Summing it can
    # exceed the entire disk even when the clones have no exclusive allocated
    # blocks, so do not present that value as physically reclaimable storage.
    return 0, bool(inventory.devices)


def _is_project_derived_data_path(path: Path, safety_root: Optional[Path]) -> bool:
    if safety_root is None:
        return False
    try:
        parts = path.resolve().relative_to(safety_root.resolve()).parts
    except (OSError, ValueError):
        return False
    direct = len(parts) == 2 and parts[1].startswith("DerivedData")
    nested = (
        len(parts) == 3
        and parts[1] in {"Build", "build"}
        and parts[2] == "DerivedData"
    )
    return (direct or nested) and (path / "info.plist").is_file() and (path / "Build").is_dir()


def path_size(path: Path) -> int:
    try:
        stat = os.stat(path, follow_symlinks=False)
    except OSError:
        return 0

    total = _allocated_size(stat)
    if path.is_symlink() or not path.is_dir():
        return total

    stack = [path]
    while stack:
        current = stack.pop()
        try:
            with os.scandir(current) as entries:
                for entry in entries:
                    try:
                        entry_stat = entry.stat(follow_symlinks=False)
                    except OSError:
                        continue
                    total += _allocated_size(entry_stat)
                    try:
                        is_dir = entry.is_dir(follow_symlinks=False)
                    except OSError:
                        is_dir = False
                    if is_dir:
                        stack.append(Path(entry.path))
        except OSError:
            continue
    return total


def modified_time(path: Path) -> Optional[datetime]:
    try:
        return datetime.fromtimestamp(os.stat(path, follow_symlinks=False).st_mtime, timezone.utc)
    except OSError:
        return None


def _safe_resolve(path: Optional[Path]) -> Optional[Path]:
    if path is None:
        return None
    try:
        return path.expanduser().resolve()
    except OSError:
        return None


def _is_default_home(home: Path) -> bool:
    return _safe_resolve(home) == _safe_resolve(Path.home())


def _is_same_or_parent(candidate: Path, path: Path) -> bool:
    if candidate == path:
        return True
    return candidate in path.parents


def _allocated_size(stat_result: os.stat_result) -> int:
    blocks = getattr(stat_result, "st_blocks", 0)
    if blocks:
        return blocks * 512
    return stat_result.st_size
