from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable, Iterator, List, Optional, Sequence, Set

from .model import ScanTarget


@dataclass(frozen=True)
class LocationSpec:
    category: str
    label: str
    relative_path: str
    cleanable: bool
    delete_mode: str
    note: str = ""


@dataclass(frozen=True)
class GlobLocationSpec:
    category: str
    label: str
    relative_glob: str
    cleanable: bool
    delete_mode: str
    note: str = ""


FIXED_LOCATIONS = (
    LocationSpec(
        "xcode-derived-data",
        "Xcode DerivedData",
        "Library/Developer/Xcode/DerivedData",
        True,
        "contents",
        "Build artifacts generated by Xcode.",
    ),
    LocationSpec(
        "xcode-module-cache",
        "Xcode module cache",
        "Library/Developer/Xcode/ModuleCache.noindex",
        True,
        "contents",
        "Compiler module cache generated by Xcode.",
    ),
    LocationSpec(
        "xcode-documentation-cache",
        "Xcode documentation cache",
        "Library/Developer/Xcode/DocumentationCache",
        True,
        "contents",
        "Downloaded and generated Xcode documentation cache.",
    ),
    LocationSpec(
        "xcode-device-support",
        "Xcode iOS DeviceSupport",
        "Library/Developer/Xcode/iOS DeviceSupport",
        True,
        "contents",
        "Device support symbols and files recreated by Xcode when needed.",
    ),
    LocationSpec(
        "xcode-device-support",
        "Xcode tvOS DeviceSupport",
        "Library/Developer/Xcode/tvOS DeviceSupport",
        True,
        "contents",
        "Device support symbols and files recreated by Xcode when needed.",
    ),
    LocationSpec(
        "xcode-device-support",
        "Xcode watchOS DeviceSupport",
        "Library/Developer/Xcode/watchOS DeviceSupport",
        True,
        "contents",
        "Device support symbols and files recreated by Xcode when needed.",
    ),
    LocationSpec(
        "xcode-device-support",
        "Xcode visionOS DeviceSupport",
        "Library/Developer/Xcode/visionOS DeviceSupport",
        True,
        "contents",
        "Device support symbols and files recreated by Xcode when needed.",
    ),
    LocationSpec(
        "xcode-archives",
        "Xcode Archives",
        "Library/Developer/Xcode/Archives",
        False,
        "none",
        "Reported only. App archives and dSYMs may be needed for releases and crash symbolication.",
    ),
    LocationSpec(
        "simulator-caches",
        "CoreSimulator caches",
        "Library/Developer/CoreSimulator/Caches",
        True,
        "contents",
        "Shared simulator cache files.",
    ),
    LocationSpec(
        "simulator-caches",
        "CoreSimulator logs",
        "Library/Logs/CoreSimulator",
        True,
        "contents",
        "Simulator log files.",
    ),
    LocationSpec(
        "brew-cache",
        "Homebrew cache",
        "Library/Caches/Homebrew",
        True,
        "contents",
        "Downloaded bottles and formula cache.",
    ),
    LocationSpec(
        "pnpm-cache",
        "pnpm store",
        "Library/pnpm/store",
        True,
        "contents",
        "Global pnpm package store. Packages are redownloaded when needed.",
    ),
    LocationSpec(
        "pnpm-cache",
        "pnpm cache",
        "Library/Caches/pnpm",
        True,
        "contents",
        "pnpm cache files.",
    ),
    LocationSpec(
        "npm-cache",
        "npm cache",
        ".npm/_cacache",
        True,
        "contents",
        "npm package tarball cache.",
    ),
    LocationSpec(
        "npm-cache",
        "npm logs",
        ".npm/_logs",
        True,
        "contents",
        "npm debug logs.",
    ),
    LocationSpec(
        "node-tool-cache",
        "node-gyp cache",
        "Library/Caches/node-gyp",
        True,
        "contents",
        "Downloaded native Node build headers.",
    ),
    LocationSpec(
        "node-tool-cache",
        "TypeScript cache",
        "Library/Caches/typescript",
        True,
        "contents",
        "TypeScript language service and tooling cache.",
    ),
    LocationSpec(
        "node-tool-cache",
        "Bun cache",
        "Library/Caches/bun",
        True,
        "contents",
        "Bun package and tooling cache.",
    ),
    LocationSpec(
        "python-cache",
        "pip cache",
        "Library/Caches/pip",
        True,
        "contents",
        "pip download and wheel cache.",
    ),
    LocationSpec(
        "python-cache",
        "pip cache",
        ".cache/pip",
        True,
        "contents",
        "pip download and wheel cache.",
    ),
    LocationSpec(
        "python-cache",
        "Poetry cache",
        "Library/Caches/pypoetry",
        True,
        "contents",
        "Poetry package cache.",
    ),
    LocationSpec(
        "python-cache",
        "Poetry cache",
        ".cache/pypoetry",
        True,
        "contents",
        "Poetry package cache.",
    ),
    LocationSpec(
        "swiftpm-cache",
        "SwiftPM cache",
        "Library/Caches/org.swift.swiftpm",
        True,
        "contents",
        "Swift Package Manager cache.",
    ),
    LocationSpec(
        "go-cache",
        "Go build cache",
        "Library/Caches/go-build",
        True,
        "contents",
        "Go build cache.",
    ),
    LocationSpec(
        "go-cache",
        "Go module cache",
        "go/pkg/mod",
        True,
        "contents",
        "Downloaded Go modules.",
    ),
    LocationSpec(
        "rust-cache",
        "Cargo registry cache",
        ".cargo/registry",
        True,
        "contents",
        "Cargo registry index, source, and crate cache.",
    ),
    LocationSpec(
        "rust-cache",
        "Cargo git cache",
        ".cargo/git",
        True,
        "contents",
        "Cargo git dependency cache.",
    ),
    LocationSpec(
        "gradle-cache",
        "Gradle cache",
        ".gradle/caches",
        True,
        "contents",
        "Gradle dependency and build caches.",
    ),
    LocationSpec(
        "gradle-cache",
        "Gradle daemons",
        ".gradle/daemon",
        True,
        "contents",
        "Gradle daemon logs and state.",
    ),
    LocationSpec(
        "gradle-cache",
        "Gradle wrapper distributions",
        ".gradle/wrapper/dists",
        True,
        "contents",
        "Downloaded Gradle wrapper distributions.",
    ),
    LocationSpec(
        "browser-cache",
        "Google browser caches",
        "Library/Caches/Google",
        True,
        "contents",
        "Browser cache files. Close browsers before cleaning for best results.",
    ),
    LocationSpec(
        "browser-cache",
        "Brave browser caches",
        "Library/Caches/BraveSoftware",
        True,
        "contents",
        "Browser cache files. Close browsers before cleaning for best results.",
    ),
    LocationSpec(
        "browser-cache",
        "Firefox browser caches",
        "Library/Caches/Firefox",
        True,
        "contents",
        "Browser cache files. Close browsers before cleaning for best results.",
    ),
    LocationSpec(
        "browser-cache",
        "Safari cache",
        "Library/Caches/com.apple.Safari",
        True,
        "contents",
        "Browser cache files. Close browsers before cleaning for best results.",
    ),
    LocationSpec(
        "docker",
        "Docker Desktop logs",
        "Library/Containers/com.docker.docker/Data/log",
        False,
        "none",
        "Reported only. Prefer Docker's own prune commands for Docker data.",
    ),
    LocationSpec(
        "docker",
        "Docker Desktop VM data",
        "Library/Containers/com.docker.docker/Data/vms",
        False,
        "none",
        "Reported only. Deleting this directly can remove images and volumes.",
    ),
    LocationSpec(
        "dev-tool-cache",
        "Codex runtime cache",
        ".cache/codex-runtimes",
        False,
        "none",
        "Reported only. Close active Codex sessions before manually clearing downloaded runtimes.",
    ),
)

GLOB_LOCATIONS = (
    GlobLocationSpec(
        "simulator-caches",
        "Simulator device caches",
        "Library/Developer/CoreSimulator/Devices/*/data/Library/Caches",
        True,
        "contents",
        "Per-device simulator app cache directories.",
    ),
)

DEFAULT_SEARCH_ROOT_NAMES = (
    "Developer",
    "Projects",
    "Code",
    "src",
    "work",
    "Sites",
    "Documents/GitHub",
)

SKIPPED_DIR_NAMES = {
    ".git",
    ".hg",
    ".svn",
    ".tox",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "Library",
}

MIN_CLEANABLE_TARGET_SIZE_BYTES = 1024 * 1024


def scan(
    home: Optional[Path] = None,
    cwd: Optional[Path] = None,
    search_roots: Optional[Sequence[Path]] = None,
    include_node_modules: bool = True,
    node_modules_older_than: Optional[timedelta] = None,
    now: Optional[datetime] = None,
) -> List[ScanTarget]:
    home = (home or Path.home()).expanduser()
    cwd = (cwd or Path.cwd()).expanduser()
    now = now or datetime.now(timezone.utc)

    targets: List[ScanTarget] = []
    targets.extend(_scan_fixed_locations(home))
    targets.extend(_scan_glob_locations(home))

    if include_node_modules:
        roots = list(search_roots) if search_roots else default_search_roots(home, cwd)
        targets.extend(_scan_node_modules(roots, node_modules_older_than, now, home))

    return sorted(targets, key=lambda item: item.size_bytes, reverse=True)


def default_search_roots(home: Path, cwd: Path) -> List[Path]:
    roots = [cwd]
    for name in DEFAULT_SEARCH_ROOT_NAMES:
        roots.append(home / name)
    return unique_existing_roots(roots, home)


def unique_existing_roots(roots: Iterable[Path], home: Optional[Path] = None) -> List[Path]:
    seen: Set[Path] = set()
    result: List[Path] = []
    home_resolved = _safe_resolve(home) if home else None
    filesystem_root = Path("/").resolve()

    for root in roots:
        path = root.expanduser()
        if not path.exists() or not path.is_dir():
            continue
        resolved = _safe_resolve(path)
        if resolved is None or resolved in seen:
            continue
        if resolved == filesystem_root:
            continue
        if home_resolved is not None and _is_same_or_parent(resolved, home_resolved):
            continue
        seen.add(resolved)
        result.append(path)

    return result


def _scan_fixed_locations(home: Path) -> Iterator[ScanTarget]:
    for spec in FIXED_LOCATIONS:
        path = home / spec.relative_path
        if path.exists():
            target = _target_from_path(
                path=path,
                category=spec.category,
                label=spec.label,
                cleanable=spec.cleanable,
                delete_mode=spec.delete_mode,
                note=spec.note,
                safety_root=home,
            )
            if target:
                yield target


def _scan_glob_locations(home: Path) -> Iterator[ScanTarget]:
    for spec in GLOB_LOCATIONS:
        for path in home.glob(spec.relative_glob):
            if path.exists():
                target = _target_from_path(
                    path=path,
                    category=spec.category,
                    label=spec.label,
                    cleanable=spec.cleanable,
                    delete_mode=spec.delete_mode,
                    note=spec.note,
                    safety_root=home,
                )
                if target:
                    yield target


def _scan_node_modules(
    roots: Sequence[Path],
    older_than: Optional[timedelta],
    now: datetime,
    home: Path,
) -> Iterator[ScanTarget]:
    cutoff = now - older_than if older_than else None
    for root in unique_existing_roots(roots, home=home):
        for path in find_node_modules(root):
            modified_at = modified_time(path)
            if cutoff and modified_at and modified_at > cutoff:
                continue
            target = _target_from_path(
                path=path,
                category="node-modules",
                label="node_modules",
                cleanable=True,
                delete_mode="tree",
                note="Project dependencies. Reinstall with npm, yarn, or pnpm.",
                safety_root=root,
            )
            if target:
                yield target


def find_node_modules(root: Path) -> Iterator[Path]:
    root = root.expanduser()
    if not root.exists() or not root.is_dir():
        return
    if root.name == "node_modules":
        yield root
        return

    for dirpath, dirnames, _filenames in os.walk(root):
        current = Path(dirpath)
        if current.name in SKIPPED_DIR_NAMES:
            dirnames[:] = []
            continue

        if "node_modules" in dirnames:
            node_modules = current / "node_modules"
            yield node_modules
            dirnames.remove("node_modules")

        dirnames[:] = [name for name in dirnames if name not in SKIPPED_DIR_NAMES]


def _target_from_path(
    path: Path,
    category: str,
    label: str,
    cleanable: bool,
    delete_mode: str,
    note: str,
    safety_root: Optional[Path],
) -> Optional[ScanTarget]:
    size = path_size(path)
    if cleanable and size < MIN_CLEANABLE_TARGET_SIZE_BYTES:
        return None
    modified_at = modified_time(path)
    return ScanTarget(
        category=category,
        label=label,
        path=path,
        size_bytes=size,
        modified_at=modified_at,
        cleanable=cleanable,
        delete_mode=delete_mode,
        note=note,
        safety_root=safety_root,
    )


def path_size(path: Path) -> int:
    try:
        stat = os.stat(path, follow_symlinks=False)
    except OSError:
        return 0

    total = _allocated_size(stat)
    if path.is_symlink() or not path.is_dir():
        return total

    stack = [path]
    while stack:
        current = stack.pop()
        try:
            with os.scandir(current) as entries:
                for entry in entries:
                    try:
                        entry_stat = entry.stat(follow_symlinks=False)
                    except OSError:
                        continue
                    total += _allocated_size(entry_stat)
                    try:
                        is_dir = entry.is_dir(follow_symlinks=False)
                    except OSError:
                        is_dir = False
                    if is_dir:
                        stack.append(Path(entry.path))
        except OSError:
            continue
    return total


def modified_time(path: Path) -> Optional[datetime]:
    try:
        return datetime.fromtimestamp(os.stat(path, follow_symlinks=False).st_mtime, timezone.utc)
    except OSError:
        return None


def _safe_resolve(path: Optional[Path]) -> Optional[Path]:
    if path is None:
        return None
    try:
        return path.expanduser().resolve()
    except OSError:
        return None


def _is_same_or_parent(candidate: Path, path: Path) -> bool:
    if candidate == path:
        return True
    return candidate in path.parents


def _allocated_size(stat_result: os.stat_result) -> int:
    blocks = getattr(stat_result, "st_blocks", 0)
    if blocks:
        return blocks * 512
    return stat_result.st_size
